server:
  port: 8080
  mode: "dev"
mysql:
  host: mysql_container
  port: 3306
  user: root
  password: root1234
  dbName: ecommerce
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_path: "./storage/logs/dev.log"
  max_size: 100
  max_backups: 7
  max_age: 7
  compress: true
redis:
  host: redis_container
  port: 6379
  password: ""
  db: 0
