server:
  port : 8080
  mode : "dev"
mysql:
  host: localhost
  port: 3307
  user: root
  password: root
  dbname: test
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_path: "./storage/logs/dev.log"
  max_size: 100
  max_backups: 7
  max_age: 7
  compress: true
  